# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbe920a2a6306bb153a5ec8afc925abd5ea4df1ceb19e598aea081dd709f434a4d9efd76b6ee63a67288bd8bb26a201034f08aadd363f02ff1fedcd856a503ab

test:
  secret_key_base: 27b410a24d68a3c677d8a48988fca7f0705e8a0cca97e18152191466866c43013be3b1f321ce247faea38ffcba6bc458f5eb7bb741ddf2500dec52f41d418fde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
